// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
const SUPABASE_URL = "https://qovziytjvskbmcowxogo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvdnppeXRqdnNrYm1jb3d4b2dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MzE2OTQsImV4cCI6MjA3NjIwNzY5NH0.LwwK5yWRbfxxpJeXteTdI1tVlD6NIXvgPoERQDkU89Q";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});