// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scwcuibrijawazbpglwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjd2N1aWJyaWphd2F6YnBnbHd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMjY5MDgsImV4cCI6MjA2MzYwMjkwOH0.KSVbzMGv2dNODuQNmU_6m02kHP-YOxUxlGgRQGCJiPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});